# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KlH3bHB2GRLmL462t1O1kyy_PR-Toh8s
"""

import requests
import matplotlib.pyplot as plt
import pandas as pd

#API_KEY = EMfWZGx9HzT3wxQk-_KRGZoAwj6Vc-IYZWnHjKxupInQKC5ZaS6_WgAtm5PQufuAvl4gJhfvpnOaKe9BcDJ-K0HiNnPukYxWATba5jLmvQt_5COidBiYCMh1IkVUZHYx

url = "https://api.yelp.com/v3/businesses/search"
headers = {
    "Authorization": 'Bearer EMfWZGx9HzT3wxQk-_KRGZoAwj6Vc-IYZWnHjKxupInQKC5ZaS6_WgAtm5PQufuAvl4gJhfvpnOaKe9BcDJ-K0HiNnPukYxWATba5jLmvQt_5COidBiYCMh1IkVUZHYx'
}

cities = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "Austin", "Jacksonville", "Fort Worth", "San Jose", "Columbus", "Charlotte", "Indianapolis", "Seattle", "San Francisco", "Denver", "Oklahoma City", "El Paso", "Nashville", "Las Vegas", "Washington", "Memphis"
"Louisville", "Detroit", "Portland", "Boston", "Baltimore"]
ratings_dict = {}

for city in cities:
  params = {
    "category": "pizza",
    "location": city
  }

  response = requests.get(url, headers=headers, params=params)
  data = response.json()

  total_ratings = 0
  num_businesses = 0

  for business in data["businesses"]:
        if "rating" in business:
            total_ratings += business["rating"]
            num_businesses += 1

  avg_rating = total_ratings / num_businesses

  ratings_dict[city] = avg_rating

ratings_dict

city = list(ratings_dict.keys())
rating = list(ratings_dict.values())

plt.bar(range(len(ratings_dict)), rating, tick_label=city)
plt.xticks(rotation = 90)
plt.title('Average Pizza Rating by City', fontsize = 18)
plt.xlabel('City', fontsize = 14)
plt.ylabel('Rating', fontsize=14)
plt.show()

df = pd.DataFrame({'City': city, 'Rating': rating})
sorted= df.sort_values('Rating', ascending=False)

plt.bar('City', 'Rating',data=sorted)
plt.xticks(rotation = 90)
plt.title('Average Pizza Rating by City', fontsize = 18)
plt.xlabel('City', fontsize = 14)
plt.ylabel('Rating', fontsize=14)
plt.show()

plt.ylim(4, 5)
plt.bar('City', 'Rating',data=sorted)
plt.xticks(rotation = 90)
plt.title('Average Pizza Rating by City', fontsize = 18)
plt.xlabel('City', fontsize = 14)
plt.ylabel('Rating', fontsize=14)
plt.show()